[build]
  # Force npm install and set ROLLUP_WASM so Rollup uses the WASM implementation on the build server
  command = "npm ci && npx cross-env ROLLUP_WASM=1 npm run build"
  publish = "dist"

[context.production.environment]
  # These should be set in Netlify UI (secure) but examples are listed here
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_PUBLISHABLE_KEY = ""
  # Force Rollup WASM in case Netlify tries to use native bindings
  ROLLUP_WASM = "1"
